### ISSUE TITLE
Native Depiction Suggestion: A way to check compatibility

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Sileo/Sileo#222]
Some way to check your iOS version to check the compatibility of packages.

**Comment by NguyenASang** [comment]
@10Meisterbaelle You can use TweakReviewsDB from Pixelomer repo (link: https://repo.pixelomer.com/).

**Comment by 10Meisterbaelle** [comment]
I am talking about something like this

**Comment by NguyenASang** [comment]
Oh that's a good idea :)

**Comment by devAgam** [comment]
> I am talking about something like this ![image](https://user-images.githubusercontent.com/45918080/165596227-7fd2b0cc-e861-47a2-ae1a-e0eb52d378e9.jpeg) Something not community based, but set by the tweak developer

That form of validation is done by the repo itself, since the iOS version is included in the request headers. Sileo does this as well but the iOS compatability range has to to specified in the control file of the package by the developer.
Like this 

`Tag: compatible_min::ios12.0, compatible_max::ios13.0
`

**Comment by 10Meisterbaelle** [comment]
> > I am talking about something like this ![image](https://user-images.githubusercontent.com/45918080/165596227-7fd2b0cc-e861-47a2-ae1a-e0eb52d378e9.jpeg) Something not community based, but set by the tweak developer
> 
> 
> 
> That form of validation is done by the repo itself since the iOS version is included in the request headers. Sileo does this as well but the iOS compatibility range has to be specified in the control file of the package by the developer or by the repo.
> 
> Like this 
> 
> 
> 
> `Tag: compatible_min::ios12.0, compatible_max::ios13.0
> 
> `

Where can I see if my iOS version is compatible if the tags are set?

**Comment by devAgam** [comment]
Fixed the control file code snippet it has to be Depends not Tags for the actual warning, and this is how it would look, not the most aesthetic but it gives a good warning
![WhatsApp Image 2022-05-02 at 9 12 03 PM](https://user-images.githubusercontent.com/46868711/166263951-884b806c-d776-4c80-a22e-cf7bced94cce.jpeg)
.

**Comment by 10Meisterbaelle** [comment]
> Fixed the control file code snippet it has to be Depends not Tags for the actual warning, and this is how it would look, not the most aesthetic but it gives a good warning
> 
> ![WhatsApp Image 2022-05-02 at 9 12 03 PM](https://user-images.githubusercontent.com/46868711/166263951-884b806c-d776-4c80-a22e-cf7bced94cce.jpeg)
> 
> .

First of all: This isn't a warning but a dependency.
Second of all: This is not a Sileo thing. It also works in Cydia and Zebra.

I would like to be able to warn my users if it might not be compatible / is not tested on this iOS version, however not block them from using it on other versions than those.

**Comment by devAgam** [comment]
> First of all: This isn't a warning but a dependency.

it is preventing users from downloading a package that is incompatible with their iOS version, users can select other versions which might be compatible with their firmware version if they exist on the repo.

> not block them from using it on other versions

You can just maintain different versions with each having their respective firmware as a dependency.

This is how a packages file from a repo look which has different versions of the same package

```
Package: com.yourcompany.compatability-test
Version: 0.0.1
...
Depends: firmware (<< 10.0)

Package: com.yourcompany.compatability-test
Version: 0.0.2
...
Depends: firmware (<< 12.0)

```





> also tell the users if the tweak has been tested on this version

This I believe is going out of the scope of a package "manager", and something that should be done explicitly by the repo (i know I'm a hypocrite), when Sileo requests for the depiction data, it does include the firmware of the device in the request in the header `x-firmware`, so the repo can modify the depiction per request.

All in all, this can definitely be a future feature update, but it's up to the Sileo development team, it might be accomplishable with the Tags since we already have `compatible_min` and `compatible_max`, maybe we can have 'incompatibility'. I'm not sure how a list of non-tested iOS versions will work thou.

**Comment by 10Meisterbaelle** [comment]
> and something that should be done explicitly by the repo (i know I'm a hypocrite), when Sileo requests for the depiction data, it does include the firmware of the device in the request in the header `x-firmware`, so the repo can modify the depiction per request.

That's interesting, didn't think about that (no repo does this, possibly because it's pretty complicated, since you need multiple depiction files). However a direct way to check would be easier.

> it might be accomplishable with the Tags since we already have compatible_min and compatible_max

Yes, but personally I think the best way to do this would be to make it possible for repos to add different text to the repo depending on the iOS version (similar to how it works in webviews).

> This I believe is going out of the scope of a package "manager", and something that should be done explicitly by the repo (i know I'm a hypocrite)

This is why I think it should be a feature in the native depiction. The currently working way is just way too complicated.

**Comment by devAgam** [comment]
>  since you need multiple depiction files)
if you are not actually "generating" JSON files at release, and generating the depictions dynamically per request, like Chariz, it should more or less be just a small modification in the content of the depiction data. if the firmware is out of the range or in an exception, just add a line to the top of the depiction stating that your iOS version is incompatible or likely incompatible. I'm not sure of the performance impact, but most server-side applications should be able to handle this quite well.

> possible for repos to add different text to the repo
not sure what you mean here

>  feature in the native depiction API.
how do you imagine it working?

**Comment by 10Meisterbaelle** [comment]
> >  since you need multiple depiction files)
> 
> 
> 
> if you are not actually "generating" JSON files at release, and generating the depictions dynamically per request, like Chariz, it should more or less be just a small modification in the content of the depiction data. if the firmware is out of the range or in an exception, just add a line to the top of the depiction stating that your iOS version is incompatible or likely incompatible. I'm not sure of the performance impact, but most server-side applications should be able to handle this quite well.
That's correct, but I'm wondering why Chariz doesn't do this.
> 
> 
> 
> > possible for repos to add different text to the repo
> 
> 
> 
> not sure what you mean here
> 
> 
> 
> >  feature in the native depiction API.
> 
> 
> 
> how do you imagine it working?

Pretty much what I mean is something similar to how you would do it in web depictions with JavaScript. It checks if you are using a specific version and puts the text in the View

**Comment by tale** [comment]
> That's correct but I'm wondering why Chariz doesn't do this.
It's because we have not felt the need to implement something like that.
There's no other reason.

**Comment by 10Meisterbaelle** [comment]
Why was it implemented in the webviews but not in the Sileo depictions?

**Comment by tale** [comment]
🤷 there's really no answer to that.

**Comment by 10Meisterbaelle** [comment]
> 🤷 there's really no answer to that.

kinda weird, but it was probably because the webview implementation was just simpler because it was done by the frontend instead of the backend

**Comment by NguyenASang** [comment]
I'm just curious how Sileo detects a higher firmware dependent package and why not use that detection to show it at the bottom of the package information like Chariz repo does?

See this image:

>  ![WhatsApp Image 2022-05-02 at 9 12 03 PM](https://user-images.githubusercontent.com/46868711/166263951-884b806c-d776-4c80-a22e-cf7bced94cce.jpeg) .

So basically, Instead of every time you need to check if a package that you can install by press the queue, we just need to but a line at the bottom of package information, Eg: This package is not compatible with your device,...

**Comment by elihwyma** [comment]
This is something that will be included in a future version, closing this issue for now. For updates follow [this](https://github.com/Sileo/Sileo/issues/255) thread
