### ISSUE TITLE
Add a way to hide the tabs in native depictions

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Sileo/Sileo#225]
Repositories should be able to hide the tabs in Sileo.
Chariz has this, however this is a special code in Sileo to change the depiction. It would have been better to implement it directly into Sileo depictions so every repo can use it.

**Comment by devAgam** [comment]
> hide the tabs in Sileo
What do you mean by tabs

**Comment by devAgam** [comment]
I think they mean `Tab object`, Chariz only has one tab. So, usually repos like Havoc, Packix, and Pluto have 2 tabs "Details", and "Changelog", Chariz doesn't have the Changelog, so they don't have the Tabs.

| <b>Pluto Repo Depiction</b>|
![4d8a7524-f896-4fc0-9e7b-06bde516df1d](https://user-images.githubusercontent.com/46868711/166476308-e5bcc309-4762-47ff-9802-86947b3cbed3.jpeg)

| <b>Chariz Depiction</b>|
![IMG_1169](https://user-images.githubusercontent.com/46868711/166477324-7153d9a9-6b36-4cc8-917b-cc9c5a601d17.png)

**Comment by 10Meisterbaelle** [comment]
> i think they mean the bottom bar

I mean the top bar, you probably just thought wrong

**Comment by 10Meisterbaelle** [comment]
> why would you think chariz has access to special secret features? and why would the sileo team implement a feature and only let one repo use it

Here's why I think that:
Here's what a native depiction on Chariz looks like:
![image](https://user-images.githubusercontent.com/45918080/166631703-b35461b6-8d46-4e6b-a9d1-a12e104ef5af.jpeg)
I downloaded this depiction (by going in the repo's packages file, copying the SileoDepiction url and saving it) and put it on my repo to test it and this is how it looks like: ![image](https://user-images.githubusercontent.com/45918080/166631893-4aec9107-ba2f-4d70-9228-f7ae40f0ef10.jpeg)
So the tabs are still here

**Comment by kirb** [comment]
Discussed this on Discord with @devAgam, but for anyone else coming across this issue, the discrepancy @10Meisterbaelle noticed was actually because Chariz returns a slightly different depiction based on the Sileo version in the user agent string.

The restriction on the root native depiction view being `DepictionTabView` was removed in Sileo 1.9 / native depiction version 0.7.1, hardcoded to only allow Chariz and a few other repos, as an initial proof-of-concept after I brought up the suggestion to the Sileo devs. All repo-specific checks were removed in Sileo 2.0 (IMO they never should have been used, but it’s in the past now). Since the native depiction format is unforgiving of things it doesn’t understand (which can cause the depiction to not be displayed at all), Chariz needs to parse the Sileo version to determine compatibility. So loading the depiction json directly in your browser will fail the checks and return a depiction compatible with Sileo 1.0 / native depiction 0.3.

This will give you the same result as you see on the arpoison package on Chariz:

```
curl https://chariz.com/api/sileo/package/arpoison/depiction.json -A 'Totally Sileo/2.3 I promise'
```

**Comment by 10Meisterbaelle** [comment]
> Discussed this on Discord with @devAgam, but for anyone else coming across this issue, the discrepancy @10Meisterbaelle noticed was actually because Chariz returns a slightly different depiction based on the Sileo version in the user agent string.
> 
> 
> 
> The requirement that the root native depiction view be a `DepictionTabView` was removed in Sileo 1.9 / native depiction version 0.7.1, as an initial proof-of-concept only for Chariz and a few other repos, after I brought up the suggestion to the Sileo devs. All repo-specific checks were removed in Sileo 2.0 (IMO they never should have been used, but it’s in the past now). Since the native depiction format is unforgiving of things it doesn’t understand (which can cause the depiction to not be displayed at all), Chariz needs to parse the Sileo version to determine compatibility. So loading the depiction json directly in your browser will fail the checks and return a depiction compatible with Sileo 1.0 / native depiction 0.3.
> 
> 
> 
> This will give you the same result as you see on the arpoison package on Chariz:
> 
> 
> 
> ```
> 
> curl https://chariz.com/api/sileo/package/arpoison/depiction.json -A 'Totally Sileo/2.3 I promise'
> 
> ```

Ok that's interesting, I'll close the issue.

**Comment by kirb** [comment]
(To avoid future confusion, I also tweaked Chariz’s user agent detection to consider web browsers the same as the latest version of Sileo)
