### ISSUE TITLE
GET button are insane slow with many tweaks installed. 

### ISSUE THREAD

**Issue by narcyzzo** [Sileo/Sileo#29]
Sileo is uselles with many tweaks installed, get button respond is 15s, is it fixed in this alpha?

**Comment by narcyzzo** [comment]
just why sileo get button getting slower by installing tweaks? cant undrestand, it letting u installing tweaks, and by that, it stopping working correctly 
i cant use sileo with this delay, anyone?

**Comment by Yamino-Kageto** [comment]
Coolstars said it was because of substrate that sileo get button was slow on checkra1n and uncover.

While i can agree with that, on the chimera bootstrap after installing 30 tweaks, the get button delay is 4 second and still imo slow

**Comment by nullpixel** [comment]
> Coolstars said it was because of substrate that sileo get button was slow on checkra1n and uncover.

Substrate would not affect get button performance at all. 

The issue here is that when you tap the get button it’s resolving deps which can be quite slow, especially if you have a lot of packages. This whole UX should be refactored so the get button shows that’s something is happening, at the very minimum.

**Comment by Cimmerian-Iter** [comment]
Yeah what installer does for exemple is that they immediately queue the tweak and take some time (usually around 2 or 3 second) for calculating the dependencies before allowing the user to press on the install button.

It should be the same UX idea for sileo. Immediately queue the tweak after pressing the get button. So then when the user will open the queu with the animation you would gain 2 second. Then the user would have to wait 2 second at most before being able to install them. So it's not as bad as to wait 4 second for the queue to show

**Comment by worldlydev** [comment]
Another possible implementation could be a loading icon like this:
https://github.com/wstyres/Zebra/issues/366

**Comment by Cimmerian-Iter** [comment]
Yeah saily use it to do the check+download in the same time right?

**Comment by worldlydev** [comment]
> Yeah saily use it to do the check+download in the same time right?

Correct. Quite a nice feature tbh.

**Comment by AvimanyuRoy3** [comment]
UI change doesn’t fix the underlying issue and merely hides it.Sileo 2 should fix that given its a major update.

**Comment by jamiebishop** [comment]
It is only a UI change that will fix this — the GET button can be slow because it needs to resolve dependencies to show them in the queue

The real fix is to make the queue appear without showing dependencies initially, then resolve them in the background. Only then should the user be able to install the queue

**Comment by coolstar** [comment]
Fixed in Sileo 1.8.4b1
